### ISSUE TITLE
Add support for serde

### ISSUE THREAD

**Issue by youainti** [tom25519/alkali#1]
I think it would be rather beneficial if this library had support for Serde, making it easy to export structs containing some of these primatives.

For example, when trying to serialize a struct with 

```rust
#[derive(Debug, Deserialize, Serialize)]
struct Test {
    a : Signature
}
```
I get the error

```rust
error[E0277]: the trait bound `[u8;64]: Serialize` is not satisfied
#[derive(Debug, Deserialize, Serialize)]
                             ^^^^^^^^^ the trait `Serialize` is not implemented for `[u8; 64]`
struct Test {
    a : Signature
    - required by a bound introduced by this call
}
```

By making the underlying types serialized in the crate, it would be much simpler to export some of the data as needed.

**Comment by tom25519** [comment]
Hey! I definitely agree, this is a feature I wanted when I first put this together. I’ll get on this in the next couple of days.

**Comment by iazel** [comment]
As far as I can see from code, this is done, isn't it?

**Comment by tom25519** [comment]
I think the issue is that Serde only implements `Serialize` and `Deserialize` for arrays of length up to 32, since the traits have to be manually implemented for each array size right now (see the [`Deserialize` impls on foreign types](https://docs.rs/serde/latest/serde/de/trait.Deserialize.html#foreign-impls)). The `Signature` type is an array of length 64, so Serde doesn't have a trait derive built-in. This is (hopefully) something the Serde team will fix when const generics get a bit more stable.

For the time being, the solution will probably involve a [remote derive](https://serde.rs/remote-derive.html). I'm not sure whether this is something I'd like within alkali's codebase or whether downstream users should do it though, which is why I've stalled on this (sorry @youainti!). The nicest solution might be to change types like `Signature` to single-element structs (like `struct Signature([u8; SIGNATURE_LENGTH])`) with a remote derive on the inner type, or just a custom Deserialize/Serialize impl for the whole type.

Any thoughts?

**Comment by tom25519** [comment]
I've gone ahead and implemented the solution I mentioned above in a commit now on main. I'm hoping to release a new version of alkali this evening, providing the CI passes :crossed_fingers:

**Comment by youainti** [comment]
Wonderful! Sorry not getting back to you, I've been really busy the last few weeks. This looks great to me.
